version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo-api-nest-crud
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - /data:/data/db

  api:
    build: .
    container_name: api-nest-crud
    ports:
      - "3000:3000"
    command: npm start
